config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'messages/create'
  root to: 'home#index'

  resources :chats, only: :show
  resources :messages, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :chat_id, :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    Telegram::StoreMessagesService.call

    @chat_id = params[:id]
    @messages = Message.where(chat_id: @chat_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    Telegram::StoreMessagesService.call

    @chats = Message.group(:chat_id).count
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    chat_id = params[:chat_id].to_i
    text = params[:text]

    message_created = Telegram::Gateway.new.send_message(chat_id, text)


    if message_created
      message = Message.new(
        chat_id: chat_id,
        text: text,
        from_chatbot: true
      )
    else
      redirect_to chat_path(chat_id), error: 'There was an error trying to create the message'
    end

    if message.save
      redirect_to chat_path(chat_id), notice: 'Reply has been sent!'
    else
      redirect_to chat_path(chat_id), error: message.errors.full_messages.to_sentence
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/show.html.erb
<div class="container">
  <h5 class="text-center">
    Chat id: </b> <%= @chat_id %>
  </h5>
  <%= link_to '< Back', root_path, class: 'btn btn-inverse' %>

  <div class="card">
    <div class="card-body chat">
      <% @messages.each do |message| %>
        <h4>
          <% if message.from_chatbot %>
            <span class="message badge bg-primary pull-right">
              <%= message.text %>
            </span>
            <br>
          <% else %>
            <span class="message badge bg-secondary">
              <%= message.text %>
            </span>
          <% end %>
        </h4>
      <% end %>

      <%= form_tag messages_path, method: :post do |f| %>
        <%= hidden_field_tag :chat_id, @chat_id %>
        <div class="form-group">
          <%= text_field_tag :text, nil, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= link_to 'Fetch Messages', chat_path(@chat_id), class: 'btn btn-info' %>
          <%= submit_tag 'Send Reply', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h2>Chats</h2>

<ul>
  <% @chats.each do |chat_id, _v| %>
    <li>
      <%= link_to "Chat #{chat_id}", chat_path(chat_id) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telegram Bot Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Telegram Bot Test</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>

    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>